/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-index.ts' */
'use strict';

export = {
  configs: {
    recommended: import('./configs/recommended'),
  },
  rules: {
    'force-await-before-async': import('./rules/force-await-before-async'),
  },
};
